name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # 手動実行も可能

# GitHub Pagesにデプロイするための権限設定
permissions:
  contents: read
  pages: write
  id-token: write

# 同時実行制限（デプロイは1つずつ）
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Pages
        uses: actions/configure-pages@v4
        with:
          enablement: true  # GitHub Pagesを自動的に有効化
        
      - name: Create deployment structure
        run: |
          # 配信用のディレクトリを作成
          mkdir -p _site
          
          # 処理済みデータをコピー
          cp -r data/processed/* _site/
          
          # CORS対応のための.htaccessファイルを作成
          cat > _site/.htaccess << 'EOF'
          # CORS設定
          Header always set Access-Control-Allow-Origin "*"
          Header always set Access-Control-Allow-Methods "GET, POST, OPTIONS"
          Header always set Access-Control-Allow-Headers "Content-Type"
          
          # JSONファイルのMIMEタイプ設定
          AddType application/json .json
          
          # キャッシュ設定
          <FilesMatch "\.(json)$">
            Header set Cache-Control "max-age=3600, public"
          </FilesMatch>
          EOF
          
          # インデックスJSONファイルを作成
          cat > _site/index.json << 'EOF'
          {
            "name": "子育て支援データ配信API",
            "description": "GovTech東京の子育て支援制度レジストリを基に、育児だGoアプリ向けに最適化されたデータを提供します。",
            "version": "1.0.0",
            "lastUpdated": "$(date -u +%Y-%m-%dT%H:%M:%S.%3NZ)",
            "endpoints": {
              "areas": {
                "description": "地域別データ",
                "pattern": "/by-area/{areaCode}.json",
                "example": "/by-area/131130.json"
              },
              "categories": {
                "description": "カテゴリ別データ",
                "pattern": "/by-category/{category}/{areaCode}.json",
                "example": "/by-category/vaccination/131130.json"
              },
              "metadata": {
                "description": "メタデータ",
                "endpoints": {
                  "areas": "/metadata/areas.json",
                  "categories": "/metadata/categories.json",
                  "versions": "/metadata/versions.json"
                }
              }
            },
            "categories": [
              {
                "id": "vaccination",
                "name": "予防接種"
              },
              {
                "id": "childcare",
                "name": "保育・一時預かり"
              },
              {
                "id": "financial",
                "name": "金銭支援"
              },
              {
                "id": "medical",
                "name": "医療・健診"
              },
              {
                "id": "education",
                "name": "教育・学習"
              },
              {
                "id": "other",
                "name": "その他"
              }
            ],
            "updateSchedule": "毎日6:00 JST",
            "sourceUrl": "https://data.storage.data.metro.tokyo.lg.jp/govtech/130001_kosodateshienseido_tokyo.json"
          }
          EOF
          
          # ファイル一覧を表示
          echo "=== Deployment structure ==="
          find _site -type f | head -20
          echo "..."
          echo "Total files: $(find _site -type f | wc -l)"
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './_site'
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4